name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          # Configure bubblewrap to use the installed JDK
          mkdir -p ~/.bubblewrap
          echo "{\"jdkPath\":\"$JAVA_HOME\",\"androidSdkPath\":\"$ANDROID_HOME\"}" > ~/.bubblewrap/config.json
          
          # Generate a dummy keystore
          keytool -genkey -v -keystore edith.keystore -alias edith -keyalg RSA -keysize 2048 -validity 10000 -storepass edith@2026 -keypass edith@2026 -dname "CN=EDITH, OU=IST, O=CTech, L=Libreville, S=Gabon, C=GA"
          
          # Build
          bubblewrap build --no-interaction --ignore-signing
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EDITH-Android-App
          path: ./*.apk
