name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        uses: is-it-ayush/pwa-to-apk@v1
        with:
          # Your PWA URL
          url: "https://edith-66y1.onrender.com"
          # (Optional) The name of the generated APK
          name: "EDITH"
          # (Optional) The package ID
          package-id: "com.edith.istctech"
          # (Optional) Display mode
          display: "standalone"
          # (Optional) Orientation
          orientation: "any"
          # (Optional) Status bar color
          theme-color: "#050a14"
          # (Optional) Background color
          background-color: "#050a14"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EDITH-Android-App
          path: ./*.apk
